### ISSUE TITLE
JEMC0006 Configuration error / VMWARE Ubuntu

### ISSUE THREAD

**Issue by heronour** [pepstock-org/jem-the-bee#20]
Hello,

I'm performing a test of jem the bee 2.2 on a VMWARE player Virtual machine with the following version of Linux Ubuntu :

jem@test-virtual-machine:~/jemhome/TEST-Env/node-000/bin$ uname -a
Linux test-virtual-machine 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I have followed the steps described on the "Advanced linux installation", but I have encountred the following problem when launching this command : 
jem.sh console

jvm 1    | 2015 07 20 02:45:42 ERROR  [WrapperSimpleAppMain] JEMC0006 Configuration error
jvm 1    | org.pepstock.jem.node.configuration.ConfigurationException: org.pepstock.jem.log.MessageException: JEMC0250 Unable to extract the interfaces by network service
jvm 1    | 	at org.pepstock.jem.node.StartUpSystem.run(StartUpSystem.java:172)
jvm 1    | 	at org.pepstock.jem.node.Main.<init>(Main.java:236)
jvm 1    | 	at org.pepstock.jem.node.Main.main(Main.java:421)
jvm 1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
jvm 1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    | 	at java.lang.reflect.Method.invoke(Method.java:606)
jvm 1    | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:290)
jvm 1    | 	at java.lang.Thread.run(Thread.java:745)
jvm 1    | Caused by: org.pepstock.jem.log.MessageException: JEMC0250 Unable to extract the interfaces by network service
jvm 1    | 	at org.pepstock.jem.util.net.InterfacesUtils.getInterface(InterfacesUtils.java:98)
jvm 1    | 	at org.pepstock.jem.node.StartUpSystem.run(StartUpSystem.java:169)
jvm 1    | 	... 8 more

Could you please help me resolve this issue ?

Thanks a lot

Regards
heronour

**Comment by stockiNail** [comment]
It seems there isn't any network interface with local host address.

Could you send the content of /etc/hosts and ifconfig for further analisys?

Thanks!

**Comment by heronour** [comment]
Hello,

It's already done, thanks StockNail, we have update the file /etc/hosts 
 
Now it works fine ;)

**Comment by stockiNail** [comment]
Very good!! :D
