### ISSUE TITLE
Create new JCL Factory

### ISSUE THREAD

**Issue by heronour** [pepstock-org/jem-the-bee#21]
I want to create a new JCL language (PowerShell) how can I proced to doing that 
thanks :)

**Comment by stockiNail** [comment]
There is already a CMD windows JCL factory, which is leveraging on ANT anyway and it could be used as example for Power shell.

https://github.com/pepstock-org/jem-the-bee/blob/master/JEM/src/org/pepstock/jem/ant/WindowsCmdFactory.java

Nevertheless we can try to implement for you, if you want.

**Comment by stockiNail** [comment]
I've implemented a PowerShellFactory. With this factory you can submit PS files as JCL.
You can set all JEM properteis and use all JEM entities if need.
ASA I'll commit, it will available. I'll come back to you with the commit ID.

**Comment by stockiNail** [comment]
commit 48c9ec7290341de7b0eadaef4e7b5aa30fd60ce0

**Comment by heronour** [comment]
Thank you very much, I appreciate that :+1:
